### ISSUE TITLE
rhead wird überschrieben

### ISSUE THREAD

**Issue by HBadertscher** [AndreasFMueller/SeminarQM#45]
In [Heisenberg, L120](https://github.com/AndreasFMueller/SeminarQM/blob/master/skript/heisenberg/main.tex#L120) wird `rhead` auf einen fixen Wert gesetzt, was zur Folge hat, dass in den hinteren Kapiteln nicht die aktuelle Section in `rhead` steht, sondern der dort gesetzte fixe Wert (_k_-Darstellung).

**Comment by AndreasFMueller** [comment]
rhead wird an 134 Stellen gesetzt. Grund ist, dass sehr oft die Titel zu lange sind. Daher ist die übliche Policy, die rhead und lhead manuell zu setzen.
