### ISSUE TITLE
Multiply defined labels and missing references

### ISSUE THREAD

**Issue by HBadertscher** [AndreasFMueller/SeminarQM#7]
The following labels are multiply defined:
- `skript:hilfssatz-winkel` in
  - Hilfssatz 4.1
  - Hilfssatz 4.3 
- `skript:eichtransformation` on
  - Equation 11.4.6
  - Equation 11.4.7
- `skript:gebundene-niveaus` on
  - Figure 14.2
  - Figure 14.3
- `skript:ewreell` in
  - Satz A.2
  - Satz A.3
- `skript:jacobi` in
  - Equation 5.3.15
  - Equation A.3.8.
- `chapter:laser` in
  - Chapter 17
  - Chapter 24

Further the following reference is undefined:
- `skript:radialgraphs-max` on page 125

**Comment by AndreasFMueller** [comment]
fixed in todays series of commits, thanks for pointing them out

**Comment by HBadertscher** [comment]
Weitere undefinierte Labels:
- `chapter:Tunneleffekt`
- `supraleitung:FeynmanDiagram1`

Und multiply defined Labels:
- `skript:Spektrum1`
- `skript:x3_Stoerung1Wellenfunktion`
- `skript:x4_Stoerung1Wellenfunktion`
